config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
get "users/show" => "users#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :rooms do
    collection do
      get "search"
    end
  end   
  resources :reservations do
    collection do
      post :confirm
    end
  end  
  resources:users  
end

app/models/room.rb
class Room < ApplicationRecord
  validates :name,presence: true
  validates :adress,presence: true
  validates :price,presence: true
  validates :introduction,presence: true,length:{maximum:200}
  has_one_attached :room_image
  belongs_to :user
  has_many :reservations
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  def index
    @rooms = Room.where(user_id: current_user.id)
  end

  def new
    @room = Room.new
  end
  
  def create
    @room = Room.new(room_params)
    if @room.save
      flash[:success] = "新規投稿をしました"
      redirect_to :rooms
    else
      flash[:danger] = "新規投稿できませんでした"
      render "new"
    end    
  end

  def show
    @room = Room.find(params[:id])
    @reservation = Reservation.new
  end  

  def edit
  end

  def update
  end

  def destroy
  end

  def search
    if params[:content] == "東京"
      @rooms = Room.where("adress like ?", "東京%")
    elsif params[:content] == "大阪"
      @rooms = Room.where("adress like ?", "大阪%")
    elsif params[:content] == "京都"
      @rooms = Room.where("adress like ?", "京都%")   
    elsif params[:content] == "北海道"
      @rooms = Room.where("adress like ?", "北海道%")       
    else  
    @q = Room.ransack(params[:q])
    @rooms = @q.result
    end
  end  

  private
  def room_params
    params.require(:room).permit(:name, :price, :introduction, :adress, :room_image, :user_id)
  end  

end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/rooms/index.html.erb
<div class="index-view">
 <div class="index-title">
  <h4>登録済みルーム一覧</h4>
</div>
  <table>
    <thead class="index-column">
      <tr>
      <th>ルーム画像</th>
      <th>ルーム名</th>
      <th>ルーム紹介</th>
      <th>料金</th>
      <th>作成日</th>
      </tr>
    </thead> 
    <tbody>
  <% @rooms.each do |room| %>
    <tr>
     <td>
     <% if room.room_image.attached? %>
      <%= image_tag room.room_image.variant(resize: "200"), class: "room-image"%>    
     <% else %>
      <img class="room-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/room01.jpg" >
     <% end %>
     </td>
     <td>
      <%= link_to room_path(room) do %>
        <%= room.name%>
      <% end %>
     </td>
     <td><%= room.introduction%></td>
     <td>¥<%= room.price%></td>
     <td><%= room.created_at%></td>
    </tr>

    </tbody>  

  <% end %>
  </table>  
</div>  

app/views/rooms/new.html.erb
<div class="view">
 <%= render "shared/error", obj: @room %> 
 <div class="nav">
  <ul>
   <li><%= link_to "基本情報", new_room_path, class:"nav-title " %></li>
  </ul>
 </div>
 <div class="form-wrapper color-form-wrapper">
  <div class= "form">
   <%= form_with model: @room do |f| %>
   <div class="setting-row">
    <h5>ルーム情報登録</h5>
   </div>
    <div class="setting-row">
      <ul>
       <li class="label"><%= f.label :name, "ルーム名" %></li>
       <li><%= f.text_field :name %></li>
      </ul>
    </div>
    <div class="setting-row">
      <ul>
       <li class="label"><%= f.label :introduction, "ルーム紹介" %></li>
       <li><%= f.text_field :introduction %></li>
      </ul>
    </div>
    <div class="setting-row">
      <ul>
       <li class="label"><%= f.label :price, "料金" %></li>
       <li><%= f.number_field :price %></li>
      </ul>
    </div>
    <div class="setting-row">
      <ul>
       <li class="label"><%= f.label :image, "住所" %></li>
       <li><%= f.text_field :adress %></li>
      </ul>
    </div>
    <div class="setting-row">
      <ul>
       <li class="label"><%= f.label :image, "ルーム画像" %></li>
       <li><%= f.file_field :room_image %></li>
      </ul>
    </div>
     <%= f.hidden_field :user_id, value: current_user.id %>
   <div class="setting-form-submit">
    <%= f.submit "登録",class: "submit" %>
   </div>
   <% end %>
  </div>
 </div>
</div>

app/views/rooms/search.html.erb
<div class="search-view">
  <h3>検索結果: <%= @rooms.count %> 件</h3>
  <div class=" results">
  <% @rooms.each do |room| %>
    <div class=" result ">
      <%= link_to room_path(room.id) do %>
      <div>
        <% if room.room_image.attached? %>
          <%= image_tag room.room_image, class:"result-image"%>
        <% else %> 
          <img class="result-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/room01.jpg">
        <% end %> 
      </div>
      <div class="result-info">
      <div class="room-detail">
        <h5><%= room.name %></h5>
        <h6><%= room.adress %></h6>
      </div>
      <div class="room-price">
        <p>¥ <%= room.price %></p>
      </div>
      </div>
    </div>
      <% end %> 
  <% end %> 
  </div>
</div> 

app/views/rooms/show.html.erb
<div class="show-view">
 <div class="room-wrapper">
  <% if @room.room_image.attached? %>
    <td><%= image_tag @room.room_image, class:"show-room-image" %>
  <% else %>
    <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/room01.jpg", class:"show-room-image" >  
  <% end %>
  <div class="room-info">
   <div class="show-user-image">
    <%= image_tag @room.user.image, class:"profile-image" %>
   </div>
   <div class="show-room-detail">
    <h5><%= @room.name %></h5>
    <p><%= @room.adress %></p>
   </div>
  </div>  
  <div class="show-room-introduction">
   <%= @room.introduction %>
  </div>
 </div>


 <div class="new-reservation">
  <h5>¥ <%= @room.price%> / 日</h5>
  <%= form_with model: @reservation, url: confirm_reservations_path, local: true do |f| %> 
   <div class="reservation-form">
    <p><%= f.label :start_date, "開始日" %></p>
    <p><%= f.datetime_field :start_date %></p>
   </div>
   <div class="reservation-form">
    <p><%= f.label :end_date, "終了日" %></p>
    <p><%= f.datetime_field :end_date %> </p>
   </div>
   <div class="reservation-form">
    <p><%= f.label :how_many, "人数" %></p>
    <p><%= f.number_field :how_many %></p>
   </div>
   <%= f.hidden_field :user_id, value: current_user.id %>
   <%= f.hidden_field :room_id, value: @room.id %>
   <%= f.submit "予約する",class: "submit" %>
  <% end %>
  </div>
</div>