config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
get "users/show" => "users#show"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  root to: "home#index"
  resources :rooms do
    collection do
      get "search"
    end
  end   
  resources :reservations do
    collection do
      post :confirm
    end
  end  
  resources:users  
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="ja">
  <head>
    <title>MinpakuApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
   <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Album example · Bootstrap v5.0</title>

    <link rel="canonical" href="https://getbootstrap.jp/docs/5.0/examples/album/">

    

    <!-- Bootstrap core CSS -->
<link href=https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/5.0/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/5.0/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/5.0/assets/img/favicons/safari-pinned-tab.svg" color="#7952b3">
<link rel="icon" href="/docs/5.0/assets/img/favicons/favicon.ico">
<meta name="theme-color" content="#7952b3">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>

    
  </head>
  <body>
    <header>
    <div class="navbar navbar-dark bg-dark shadow-sm">
     <div class="container">
      <div class="header-left">
       <div class="top-link-icon">
       <%= link_to "/" do%>
       <img src="https://presite-potepancamp-rails-02.herokuapp.com/assets/logo.png">
       <% end %>
       </div>
       <div class="header-search">
          <%= search_form_for @q,url: search_rooms_path  do |f| %>
            <%= f.search_field :adress_cont, placeholder: "エリア" %>
            <%= f.search_field :name_or_adress_cont, placeholder: "キーワード" %>
            <%= f.submit class:"header-search-button "%>
          <% end %>
       </div>
      </div>
      <div class="header-right">
       <% if user_signed_in? %>
       <div class="dropdown">
        <div class="name">
         <%= current_user.name %>
        </div>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader" aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation" data-toggle="dropdown">
        <% if current_user.image.attached? %>
          <%= image_tag current_user.image,:class=>"header-image"%>
        <% else %> 
          <img class="header-image" src="https://presite-potepancamp-rails-02.herokuapp.com/assets/default_icon-9263fc59c414b7228d256fc178dcb22183561357950a68f5ad086ba7ee054974.jpg">
        <% end %>  
        </button>
        <ul class="dropdown-menu" role="menu">
		      <li role="presentation"><%= link_to "ルーム登録", new_room_path, class:"nav-list" %></li>
		      <li role="presentation"><%= link_to "予約済みルーム", reservations_path, class:"nav-list"%></li>
		      <li role="presentation"><%= link_to "登録済みルーム", rooms_path, class:"nav-list"%></li>
		      <li role="presentation"><%= link_to "設定", edit_user_path(current_user), class:"nav-list" %></li>
		      <li role="presentation"><%= link_to "ログアウト", destroy_user_session_path, method: :delete, class:"nav-list" %></li>
	     </ul>
      </div>
      <% else %>
        <button class="header-button login"><%= link_to "ログイン",  new_user_session_path %></button>
        <button class="header-button signin"><%= link_to "登録する",  new_user_registration_path %></button>
      <% end %> 
      </div>
    </header>
     <%= render 'shared/flash_message' %>
   <!--<p class="notice"><%= notice %></p>-->
   <!--<p class="alert"><%= alert %></p>-->
    <%= yield %>

    <footer class="py-5">
      <div class="container">
        <p>© 2020 POTEPAN.INC.</p>
      </div>
    </footer>
  </body>
</html>